### ISSUE TITLE
InitializationFailure Callback - "error parsing metadata"

### ISSUE THREAD

**Issue by cyberformed** [VdoCipher/sample-android-app#8]
After uploaded the videos into my control panel, I have copied the video ID and client key from control panel. InitializationFailure Callback - **error parsing metadata** when I am trying to run the application by passing the **Video ID** and **clientSecretKey**. 

Help required in this regard ASAP

**Comment by vibhavsinha** [comment]
Hello @cyberformed 

Can you please provide the code around initialization and initParams that you are using?
